---
- src: https://github.com/carlosfrias/apigee-opdk-setup-component-installer

- src: https://github.com/carlosfrias/apigee-opdk-setup-default-settings

- src: https://github.com/carlosfrias/apigee-opdk-set-reachable

- src: https://github.com/carlosfrias/apigee-fetch-files

- src: https://github.com/carlosfrias/apigee-opdk-setup-status

- src: https://github.com/carlosfrias/apigee-opdk-start-component

- src: https://github.com/carlosfrias/apigee-opdk-stop-components

- src: https://github.com/carlosfrias/apigee-opdk-backup

- src: https://github.com/carlosfrias/apigee-opdk-restore

- src: https://github.com/carlosfrias/apigee-opdk-server-self

- src: https://github.com/carlosfrias/apigee-opdk-update-component

- src: https://github.com/carlosfrias/apigee-opdk-setup-bootstrap
