---
- name: Update cache and ensure components are running
  hosts: planet
  gather_facts: no
  tags: ['apigee-pre-req']
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role: apigee-opdk-setup-default-settings, tags: ['cache'] }
  - { role: apigee-opdk-start-components, tags: ['start'] }
  - { role: apigee-opdk-setup-java-home, tags: ['java_home'] }
  - { role: apigee-opdk-setup-bootstrap, tags: ['apigee-bootstrap'], upgrade_edge: true }
  - { role: apigee-opdk-setup-component-installer, tags: ['apigee-component'], upgrade_edge: true }


- name: Upgrade Cassandra
  hosts: ds
  serial: 1
  tags: ['ds']
  gather_facts: no
  vars:
    upgrade_component: cs,zk
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component {{ upgrade_component }} on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-update-component, apigee_component: '{{ upgrade_component }}' }

- name: Upgrade Qpid
  hosts: qpid
  serial: 1
  gather_facts: no
  tags: ['qpid']
  vars:
    server_type_names: ['qs']
    upgrade_component: qpid
    block_port: '{{ qpid_messaging_port }}'
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component {{ upgrade_component }} on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: '{{ server_type_names }}' }
  - { role: apigee-opdk-iptables-port-block, destination_port: '{{ block_port }}' }
  - { role: apigee-opdk-update-component,  apigee_component: '{{ upgrade_component }}' }
  - { role: apigee-opdk-iptables-flush }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: '{{ server_type_names }}' }

- name: Upgrade Ldap
  hosts: ldap
  tags: ['ldap']
  serial: 1
  gather_facts: no
  vars:
    hosts: ldap
    upgrade_component: ldap
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component {{ upgrade_component }} on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-update-component, apigee_component: '{{ upgrade_component }}' }

- name: Upgrade Qpid Edge Components
  hosts: qpid
  serial: 1
  gather_facts: no
  tags: ['qpid_edge']
  vars:
    upgrade_component: edge
    block_port: '{{ qpid_messaging_port }}'
    server_types: ['qs']
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component {{ upgrade_component }} on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: '{{ server_type_names }}' }
  - { role: apigee-opdk-iptables-port-block, destination_port: '{{ block_port }}' }
  - { role: apigee-opdk-update-component, apigee_component: '{{ upgrade_component }}' }
  - { role: apigee-opdk-iptables-flush }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: '{{ server_type_names }}' }


- name: Upgrade Management Server Edge Components
  hosts: ms
  serial: 1
  gather_facts: no
  tags: ['ms_edge']
  vars:
    upgrade_component: edge
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component {{ upgrade_component }} on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-update-component,  apigee_component: '{{ upgrade_component }}' }

- name: Upgrade Router & Message Processor
  hosts: rmp
  serial: 1
  gather_facts: no
  tags: ['rmp']
  vars:
    server_type_names: ['router', 'mp']
    upgrade_component: edge
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component {{ upgrade_component }} on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: '{{ server_type_names }}' }
  - { role: apigee-opdk-update-component,  apigee_component: '{{ upgrade_component }}' }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: '{{ server_type_names }}' }

- name: Upgrade UI
  hosts: ui
  serial: 1
  gather_facts: no
  tags: ['ui']
  vars:
    upgrade_component: ui
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component {{ upgrade_component }} on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-update-component,  apigee_component: '{{ upgrade_component }}' }

- name: Upgrade PG in dc1
  include: upgrade-postgres.yml
  tags: ['pg']

- include: opdk-setup-log-files.yml
  vars:
    hosts: dc1-ds
  tags: ['logs']

- include: opdk-setup-log-files.yml
  vars:
    hosts: dc2-ds
  tags: ['logs']

- include: opdk-setup-log-files.yml
  vars:
    hosts: dc1-ms
  tags: ['logs']

- include: opdk-setup-log-files.yml
  vars:
    hosts: dc2-ms
  tags: ['logs']

- include: opdk-setup-log-files.yml
  vars:
    hosts: dc1-rmp
  tags: ['logs']

- include: opdk-setup-log-files.yml
  vars:
    hosts: dc2-rmp
  tags: ['logs']

- include: opdk-setup-log-files.yml
  vars:
    hosts: dc1-qpid
  tags: ['logs']

- include: opdk-setup-log-files.yml
  vars:
    hosts: dc2-qpid
  tags: ['logs']

- include: opdk-setup-log-files.yml
  vars:
    hosts: dc1-pgmaster
  tags: ['logs']

- include: opdk-setup-log-files.yml
  vars:
    hosts: dc2-pgmaster
  tags: ['logs']

- include: opdk-setup-log-files.yml
  vars:
    hosts: dc1-pgstandby
  tags: ['logs']

- include: opdk-setup-log-files.yml
  vars:
    hosts: dc2-pgstandby
  tags: ['logs']

