---
- name: Update the ansible cache
  hosts: planet
  tags: ['cache']
  gather_facts: no
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-default-settings

- name: Rolling back installation and bootstrap
  hosts: '{{ hosts }}'
  gather_facts: no
  vars:
    remove_apigee: true
    opdk_version: 4.16.01
  roles:
  - apigee-opdk-setup-bootstrap-rollback

- name: Bootstap to the specified version on attribute opdk_version
  include: components/opdk-install-component.yml
  vars:
    opdk_version: 4.16.01
    component_profile: "{{ component }}"
    upgrade_edge: true
