---
- name: Update Ansible cache
  include: configuration/update_cache.yml
  tags:
  - cache

- name: All components should be running
  hosts: planet
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  tasks:
  - name: All components should be running
    shell: "{{ apigee_all }} start"
  tags:
  - started

- name: Upgrade DC-1 Cassandra
  include: components/opdk-upgrade-component.yml
  vars:
    update_apigee_service: true
    hosts: ds
    upgrade_component: cs,zk
  tags:
  - cs-zk

- name: Upgrade DC-1 qpid
  include: components/opdk-iptables-block.yml
  vars:
    update_apigee_service: true
    hosts: qpid
    server_type_name: qs
    upgrade_component: edge
  tags:
  - qpid

- name: Upgrade DC-1 ldap
  include: components/opdk-upgrade-component.yml
  vars:
    update_apigee_service: true
    hosts: ldap
    upgrade_component: ldap
  tags:
  - ldap

- name: Upgrade DC-1 ms
  include: components/opdk-upgrade-component.yml
  vars:
    update_apigee_service: true
    hosts: qpid,ms
    upgrade_component: edge
  tags:
  - qpid

- name: Upgrade DC-1 rmp
  include: components/opdk-upgrade-reachability-component.yml
  vars:
    update_apigee_service: true
    hosts: rmp
    server_type_name: router
    upgrade_component: edge
  tags:
  - rmp

- name: Upgrade DC-1 ui
  include: components/opdk-upgrade-component.yml
  vars:
    update_apigee_service: true
    hosts: ui
    upgrade_component: ui
  tags:
  - ui

- name: Stop DC-1 Postgres components
  hosts: ps
  roles:
  - { role:  apigee-opdk-stop-components, component_name: 'edge-postgres-server', tags: ['pg']}
  - { role:  apigee-opdk-stop-components, component_name: 'apigee-postgresql', tags: ['pg'] }

- name: Stop DC-1 Qpid components
  hosts: qpid
  roles:
  - { role:  apigee-opdk-stop-components, component_name: 'edge-qpid-server', tags: ['pg'] }

- name: Upgrade DC-1 PS component
  include: components/opdk-upgrade-component.yml
  vars:
    update_apigee_service: true
    hosts: pgmaster
    server_type_name: ps
    upgrade_component: ps
  tags:
  - pg

- name: Upgrade DC-1 Postgres master
  hosts: pgmaster
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  tasks:
  - name: PGMaster DB upgrade
    shell: '{{ apigee_service }} apigee-postgresql db_upgrade'
    tags:
    - pg

- name: Upgrade DC-1 Postgres standby
  include: components/opdk-upgrade-component.yml
  vars:
    update_apigee_service: true
    hosts: pgstandby
    server_type_name: ps
    upgrade_component: ps
  tags:
  - pg

- name: Start DC-1 Postgres components
  hosts: ps
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role:  apigee-opdk-start-components, component_name: 'edge-postgres-server', tags: ['pg']  }
  - { role:  apigee-opdk-start-components, component_name: 'apigee-postgresql', tags: ['pg']  }

- name: Start DC-1 Qpid components
  hosts: qpid
  roles:
  - { role:  apigee-opdk-start-components, component_name: 'edge-qpid-server', tags: ['pg']  }

- name: Validate that DC-1 PG Master is master
  hosts: pgmaster
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  tasks:
  - name: Validate this is postgresql master
    shell: "{{ apigee_service }} apigee-postgresql postgres-check-master"
    tags:
    - pg

- name: Setup and Validate that DC-1 PG Standby is standby
  hosts: pgstandby
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  tasks:
  - name: Remove pgdata folder
    file:
      path: "{{ apigee_installation_home}}/data/apigee-postgresql/pgdata"
      state: absent
    tags:
    - pg

  - name: Setup replication standby
    shell: "{{ apigee_service }} apigee-postgresql setup-replication-on-standby -f {{ opdk_installation_config_file }}"
    tags:
    - pg

  - name: Validate this is postgresql standby
    shell: "{{ apigee_service }} apigee-postgresql postgres-check-standby"
    tags:
    - pg

- name: Upgrade DC-1 PG with edge for remaining components
  include: components/opdk-upgrade-component.yml
  vars:
    update_apigee_service: true
    hosts: pg
    upgrade_component: edge
  tags:
  - pg
