---
- name: Update Ansible cache
  include: configuration/update_cache.yml
  tags:
  - cache

- name: All components should be running
  hosts: planet
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  tasks:
  - name: All components should be running
    shell: "{{ apigee_all }} start"
    tags:
    - started

- name: Update the installer for planet
  include: components/opdk-update-installer.yml
  vars:
    hosts: planet
    upgrade_edge: true
  tags:
  - installer

- name: Upgrade Cassandra
  include: components/opdk-upgrade-component.yml
  vars:
    upgrade_edge: true
    hosts: ds
    upgrade_component: cs,zk
  tags:
  - cs-zk

- name: Upgrade qpid
  include: components/opdk-upgrade-component.yml
  vars:
    upgrade_edge: true
    hosts: qpid
    server_type_names:
    - qs
    upgrade_component: qpid
    block_port: '{{ qpid_messaging_port }}'
  tags:
  - qpid_only

- name: Upgrade ldap
  include: components/opdk-upgrade-component.yml
  vars:
    upgrade_edge: true
    hosts: ldap
    upgrade_component: ldap
  tags:
  - ldap

- name: Upgrade ms
  include: components/opdk-upgrade-component.yml
  vars:
    upgrade_edge: true
    hosts: qpid,ms
    upgrade_component: edge
    block_port: '{{ qpid_messaging_port }}'
  tags:
  - qpid_edge

- name: Upgrade rmp
  include: components/opdk-upgrade-component.yml
  vars:
    server_type_names:
    - router
    - mp
    upgrade_edge: true
    hosts: rmp
    upgrade_component: edge
  tags:
  - rmp_edge

- name: Upgrade ui
  include: components/opdk-upgrade-component.yml
  vars:
    upgrade_edge: true
    hosts: ui
    upgrade_component: ui
  tags:
  - ui

- name: Stop Postgres components
  hosts: pg
  gather_facts: no
  tags: ['pg']
  roles:
  - { role:  apigee-opdk-stop-components, component_name: 'edge-postgres-server', tags: ['pg']}
  - { role:  apigee-opdk-stop-components, component_name: 'apigee-postgresql', tags: ['pg'] }

- name: Stop Qpid components
  gather_facts: no
  hosts: qpid
  roles:
  - { role:  apigee-opdk-stop-components, component_name: 'edge-qpid-server', tags: ['pg'] }

- name: Upgrade PS component
  include: components/opdk-upgrade-component.yml
  vars:
    upgrade_edge: true
    hosts: pgmaster
    server_type_name: ps
    upgrade_component: ps
  tags:
  - pg

- name: Upgrade Postgres master
  hosts: pgmaster
  gather_facts: no
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  tasks:
  - name: PGMaster DB upgrade
    shell: '{{ apigee_service }} apigee-postgresql db_upgrade'
    tags:
    - pg

- name: Upgrade Postgres standby
  include: components/opdk-upgrade-component.yml
  vars:
    upgrade_edge: true
    hosts: pgstandby
    server_type_name: ps
    upgrade_component: ps
  tags:
  - pg

- name: Start Postgres components
  hosts: ps
  serial: 1
  tags: ['pg']
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role:  apigee-opdk-start-components, component_name: 'edge-postgres-server', tags: ['pg']  }
  - { role:  apigee-opdk-start-components, component_name: 'apigee-postgresql', tags: ['pg']  }

- name: Start Qpid components
  hosts: qpid
  tags: ['pg']
  roles:
  - { role:  apigee-opdk-start-components, component_name: 'edge-qpid-server', tags: ['pg']  }

- name: Validate that PG Master is master
  hosts: pgmaster
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  tasks:
  - name: Validate this is postgresql master
    shell: "{{ apigee_service }} apigee-postgresql postgres-check-master"
    tags:
    - pg

- name: Setup and Validate that PG Standby is standby
  hosts: pgstandby
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  tasks:
  - name: Remove pgdata folder
    file:
      path: "{{ apigee_installation_home}}/data/apigee-postgresql/pgdata"
      state: absent
    tags:
    - pg

  - name: Setup replication standby
    shell: "{{ apigee_service }} apigee-postgresql setup-replication-on-standby -f {{ opdk_installation_config_file }}"
    tags:
    - pg

  - name: Validate this is postgresql standby
    shell: "{{ apigee_service }} apigee-postgresql postgres-check-standby"
    tags:
    - pg

- name: Upgrade PG with edge for remaining components
  include: components/opdk-upgrade-component.yml
  vars:
    upgrade_edge: true
    hosts: pg
    upgrade_component: edge
  tags:
  - pg
