---
- hosts: '{{ hosts }}'
  serial: 1
  gather_facts: no
  roles:
  - apigee-opdk-setup-java-home
  - apigee-opdk-setup-bootstrap
  - { role: 'apigee-opdk-setup-component-installer', upgrade_edge: true }
