---
- hosts: '{{ hosts }}'
  serial: 1
  gather_facts: no
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-java-home
  - apigee-opdk-setup-bootstrap
  - apigee-opdk-setup-component-installer
