---
- hosts: '{{ hosts }}'
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - { role: apigee-opdk-set-reachable, reachability: '{{ reachability_setting | bool }}', server_type: '{{ server_type_name }}' }
