---
- hosts: '{{ hosts }}'
  vars:
    opdk_version: 4.16.09
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-bootstrap
  - apigee-opdk-setup-component-installer
#  - { role: apigee-opdk-setup-component, profile: '{{ component_profile }}' }
  - { role: apigee-opdk-update-component, apigee_component: '{{ upgrade_component }}' }
