---
- hosts: '{{ hosts }}'
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-bootstrap
  - apigee-opdk-setup-component-installer
  - { role: apigee-opdk-update-component, apigee_component: '{{ upgrade_component }}' }
