---
- hosts: '{{ hosts }}'
  serial: 1
  gather_facts: no
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - {
      role: apigee-opdk-set-reachable,
      reachability: False,
      server_types: '{{ server_type_names }}',
      when: server_type_names is defined
    }
  - {
      role: apigee-opdk-iptables-port-block,
      destination_port: '{{ block_port }}',
      when: block_port is defined
    }
  - {
      role: apigee-opdk-update-component,
      apigee_component: '{{ upgrade_component }}'
    }
  - {
      role: apigee-opdk-iptables-flush,
      when: block_port is defined
    }
  - {
      role: apigee-opdk-set-reachable,
      reachability: True,
      server_types: '{{ server_type_names }}',
      when: server_type_names is defined
    }
